# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Buld

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
        cache-dependency-path: backend/go.sum
     
    - name: Build
      run: |
        cd backend
        go build -buildmode exe
        
    - name: Upload Go
      uses: actions/upload-artifact@v3
      with:
        name: exe
        path: ${{ github.workspace }}/backend/*.exe
