# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Buld

on:
  workflow_dispatch:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
        cache-dependency-path: backend/go.sum
     
    - name: Build
      run: |
        cd backend
        env GOOS=windows GOARCH=amd64 go build -o ${{ github.workspace }}/backend/kogalym-backend.exe main.go

    - name: Prepare Artifacts
      run: |
        cd backend
        mkdir artifacts
        cp kogalym-backend.exe ${{ github.workspace }}/backend/artifacts
        cp .env  ${{ github.workspace }}/backend/artifacts
    
    - name: Upload Go
      uses: actions/upload-artifact@v3
      with:
        name: WindowsExeFiles
        path: ${{ github.workspace }}/backend/artifacts
